version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.9"
    APP_NAME: "todo-api"
    FRONTEND_URL: "http://localhost:3000"

  secrets-manager:
    DB_USER:     dev-db-credentials-6:db_user
    DB_PASSWORD: dev-db-credentials-6:db_password
    DB_NAME:     dev-db-credentials-6:db_name
    

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt pytest flake8

  pre_build:
    commands:
      - echo "Linting..."
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127
      - echo "Checking DB connection..."
      - |
        python -c "import os, sys, mysql.connector; ..."

  build:
    commands:
      - echo "Running tests..."
      - pytest tests/           # build will stop here if tests fail
      - echo "Preparing build artifact..."
      - rm -rf build && mkdir build
      - cp -r --parents $(find . -type f -not -path './build/*') build/
      - cd build
      - rm -rf .git __pycache__ *.pyc tests/

cache:
  paths:
    - '/root/.cache/pip/**/*'

reports:
  pytest-report:
    files:
      - '**/coverage.xml'
    file-format: Cobertura

artifacts:
  files:
    - '**/*'
