version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.10"
    APP_NAME: "todo-api"
    FRONTEND_URL: "http://localhost:3000"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt pytest flake8

  pre_build:
    commands:
      - echo "Linting..."
      - echo "Skipping DB connection test in CodeBuild..."

  build:
    commands:
      - echo "Running tests..."
      - pytest tests/                     # build fails if tests fail
      - echo "Preparing build artifact..."
      - rm -rf build && mkdir build
      - cp -r --parents $(find . -type f -not -path './build/*') build/
      - cd build
      - rm -rf .git __pycache__ *.pyc tests/

artifacts:
  base-directory: build
  files:
    - '**/*'
  name: ${APP_NAME}-$(date +%Y-%m-%d-%H-%M-%S)
