version: 0.2

env :
  parameter-store:
    DB_HOST: /dev/db/endpoint
  secrets-manager:
    DB_CREDENTIALS: dev-db-credentials-00

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install awscli
      - pip install jq
      
  pre_build:
    commands:
      - echo "Retrieving secrets and parameters..."
      - export DB_CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id dev-db-credentials-00 --query 'SecretString' --output text)
      - export DB_USER=$(echo $DB_CREDENTIALS | jq -r '.username')
      - export DB_PASSWORD=$(echo $DB_CREDENTIALS | jq -r '.password')
      - export DB_HOST=$(aws ssm get-parameter --name /dev/db/endpoint --query 'Parameter.Value' --output text)
      - echo "Running tests..."
      - python -m pytest tests/ || exit 0
      
  build:
    commands:
      - echo "Starting build phase..."
      - python -m pylint --fail-under=7 *.py || exit 0
      
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
    - .env
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip'