version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Fetching DB host from Parameter Store..."
      - DB_HOST=$(aws ssm get-parameter \
          --name "/dev/db/endpoint" \
          --with-decryption \
          --region us-east-1 \
          --query "Parameter.Value" \
          --output text)

      - echo "Fetching DB credentials from Secrets Manager..."
      - SECRET_JSON=$(aws secretsmanager get-secret-value \
          --secret-id "dev-db-credentials-00" \
          --region us-east-1 \
          --query SecretString \
          --output text)

      - DB_USER=$(echo $SECRET_JSON | jq -r .db_user)
      - DB_PASSWORD=$(echo $SECRET_JSON | jq -r .db_password)
      - DB_NAME=$(echo $SECRET_JSON | jq -r .db_name)

      - echo "Creating .env file..."
      - echo "DB_HOST=$DB_HOST"       >> .env
      - echo "DB_USER=$DB_USER"       >> .env
      - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
      - echo "DB_NAME=$DB_NAME"       >> .env

  build:
    commands:
      - echo "Running backend build logic..."
      - cat .env  # Just for verification (remove in production)
      - python -m unittest discover tests  # if you have tests

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
