version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.10"
    APP_NAME: "todo-api"
    FRONTEND_URL: "http://localhost:3000"

  parameter-store:
    DB_HOST: /dev/db/endpoint            # <-- your Parameter Store key

  secrets-manager:
    DB_USER:     dev-db-credentials-00:db_user
    DB_PASSWORD: dev-db-credentials-00:db_password
    DB_NAME:     dev-db-credentials-00:db_name

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python -m pip install --upgrade pip
      - python -m pip install virtualenv
      - virtualenv venv
      - . venv/bin/activate
      - pip install --no-cache-dir pytest==7.4.0 pytest-cov==4.1.0 pytest-junit
      - pip install --no-cache-dir -r requirements.txt
      - pip install --no-cache-dir awscli jq
      
  pre_build:
    commands:
      - . venv/bin/activate  # Ensure virtual environment is activated
      - echo "Retrieving secrets and parameters..."
      - export DB_CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id dev-db-credentials-00 --query 'SecretString' --output text)
      - export DB_USER=$(echo $DB_CREDENTIALS | jq -r '.username')
      - export DB_PASSWORD=$(echo $DB_CREDENTIALS | jq -r '.password')
      - export DB_HOST=$(aws ssm get-parameter --name /dev/db/endpoint --query 'Parameter.Value' --output text)
      - echo "Running tests..."
      - python -m pytest tests/ --cov=. --cov-report=xml || echo "Tests failed but continuing build"
      
  build:
    commands:
      - . venv/bin/activate  # Ensure virtual environment is activated
      - echo "Starting build phase..."
      - echo "Linting code..."
      - python -m pylint --fail-under=7 *.py || echo "Linting failed but continuing build"
      - echo "Preparing build artifact..."
      - rm -rf build && mkdir build
      - cp -r --parents $(find . -type f -not -path './build/*') build/
      - cd build
      - rm -rf .git __pycache__ *.pyc tests/

cache:
  paths:
    - '/root/.cache/pip/**/*'

reports:
  pytest-report:
    files:
      - '**/coverage.xml'
    file-format: Cobertura

artifacts:
  files:
    - server.py
    - requirements.txt
    - scripts/**/*
    - appspec.yml
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip'