version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.10"
    APP_NAME: "todo-api"
    FRONTEND_URL: "http://localhost:3000"

  parameter-store:
    DB_HOST: /dev/db/endpoint

  secrets-manager:
    DB_USER: dev-db-credentials-00:db_user
    DB_PASSWORD: dev-db-credentials-00:db_password
    DB_NAME: dev-db-credentials-00:db_name

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install awscli pylint jq pytest pytest-cov

  pre_build:
    commands:
      - . venv/bin/activate
      - echo "Retrieving secrets and parameters..."
      - export DB_CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id dev-db-credentials-00 --query 'SecretString' --output text)
      - export DB_USER=$(echo $DB_CREDENTIALS | jq -r '.username')
      - export DB_PASSWORD=$(echo $DB_CREDENTIALS | jq -r '.password')
      - export DB_NAME=$(echo $DB_CREDENTIALS | jq -r '.dbname')  # optional
      - export DB_HOST=$(aws ssm get-parameter --name /dev/db/endpoint --query 'Parameter.Value' --output text)
      - echo "Checking DB connectivity..."
      - nc -zv $DB_HOST 3306 || echo "Warning: DB not reachable"
      - echo "Running tests..."
      - python -m pytest tests/ || exit 0

  build:
    commands:
      - . venv/bin/activate
      - echo "Starting build phase..."
      - mkdir -p tests
      - python -m pylint --fail-under=7 *.py || echo "Linting check completed"

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip'
